### ISSUE TITLE
MS MARCO evaluation results are far different.

### ISSUE THREAD

**Issue by SHi-ON** [nyu-dl/dl4marco-bert#12]
After running the [evaluation script](https://github.com/dfcf93/MSMARCO/blob/master/Ranking/Baselines/msmarco_eval.py) on my trained model's prediction using [dev qrels](https://msmarco.blob.core.windows.net/msmarcoranking/qrels.dev.tsv), MRR@10 is way off than the leaderboard (including your reported numbers). This is the output of running the script on the predictions from [your provided trained model](https://drive.google.com/open?id=1crlASTMlsihALlkabAQP6JTYIZwC1Wm8) and also mine:

```
[sa1149@dsci-g1 marcoEval]$ python msmarco_eval.py ../data/qrels.dev.tsv nyu_dl-msmarco_predictions_dev.tsv 
#####################
MRR @10: 0.0459997803744431
QueriesRanked: 6980
#####################
[sa1149@dsci-g1 marcoEval]$ python msmarco_eval.py ../data/qrels.dev.tsv shi_on-msmarco_predictions_dev.tsv 
#####################
MRR @10: 0.04420699037588809
QueriesRanked: 6980
#####################
[sa1149@dsci-g1 marcoEval]$ 
```

[Here](https://colab.research.google.com/drive/1AB8icm1halIkxRayhFBTsQu8V1U_302_) is the link to my copy of Colab.

Is there anything that can explain these differences?

**Comment by rodrigonogueira4** [comment]
You need to eval using `qrels.dev.small.tsv` as this is the file MS MARCO organizers use to compute numbers in the leaderboard. 

I've opened a ticket regarding this:
https://github.com/dfcf93/MSMARCO/issues/29

**Comment by SHi-ON** [comment]
Thanks for your quick response! 

We need to wait for the MS team, but in the meantime, does that MRR@10 number that I've got from your provided trained model make sense?

**Comment by rodrigonogueira4** [comment]
MRR@10 0.04? I think so. 

In your colab, MRR@10 = ~0.355 for half of the dev queries (3320), so I think your trained model (gs://buck-albert/msmarco-bert/init/model.ckpt-350000.meta) is in good shape.

**Comment by rodrigonogueira4** [comment]
BTW, you can download qrels.dev.small.tsv here:
https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz

**Comment by spacemanidol** [comment]
Confirmed. The target file is qrels.*.small.tsv 

The top1000s we have publicly are 1/10 of the full size. Ill update documentration

**Comment by SHi-ON** [comment]
> MRR@10 0.04? I think so.
> 
> In your colab, MRR@10 = ~0.355 for half of the dev queries (3320), so I think your trained model (gs://buck-albert/msmarco-bert/init/model.ckpt-350000.meta) is in good shape.

Thanks for getting back to me on this.

**Comment by amirj** [comment]
I'm using [py_treceval](https://github.com/cvangysel/pytrec_eval) and got different MRR for the same run file (<qid>\t<pid>\t<rank>). 
Why the evaluation script depends on the size of the qrel file? I mean, it should calculate MRR for the retrieved queries (any subset of qre.dev.tsv queries), Isn't it?
