### ISSUE TITLE
How many step did you train?

### ISSUE THREAD

**Issue by Albert-Ma** [nyu-dl/dl4marco-bert#13]
As you mentioned in `README.md`, the max_steps you set is 400, 000. But this will only travel about 1/4 data in the `triples.small`. Did these steps can get the score 0.35 as you submitted to the MSMARCO, since I do not have so much computational resources, so I want to make sure how many steps could get a high MRR score.

Thanks.

**Comment by rodrigonogueira4** [comment]
Yes, 400k training steps are already enough to reach 36.5 on the dev set. 
Please check figure 1 in the paper (https://arxiv.org/pdf/1901.04085.pdf). With 40k steps you should be able to reach at least 34.5.
