### ISSUE TITLE
Bert Base Weights

### ISSUE THREAD

**Issue by oisin-dolphin** [nyu-dl/dl4marco-bert#14]
Hi,

Really awesome paper!

Is there any chance you can release the ms marco bert base checkpoint in addition to the bert large checkpoint?

**Comment by rodrigonogueira4** [comment]
Sure, here you go:

https://drive.google.com/open?id=1cyUrhs7JaCJTTu-DjFUqP6Bs4f8a6JTX

This BERT Base was trained on MS MARCO.
