### ISSUE TITLE
have no access

### ISSUE THREAD

**Issue by xusongpei** [nyu-dl/dl4marco-bert#19]
when i use the colab you provided, something wrong, i don't know why

Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://xusongpei1995/output/model.ckpt-0: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to xusongpei1995."
   }
  ],
  "code": 403,
  "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to xusongpei1995."
 }
}
'
	 when reading gs://xusongpei1995/output
	 [[{{node save/RestoreV2}}]]

**Comment by xusongpei** [comment]
E0623 22:09:49.396769 139633880581888 error_handling.py:70] Error recorded from infeed: From /job:worker/replica:0/task:0:
Error executing an HTTP request: HTTP response code 404 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "No such object: xusongpei1995/dataset_train.tf"
   }
  ],
  "code": 404,
  "message": "No such object: xusongpei1995/dataset_train.tf"
 }
}
'
	 when reading metadata of gs://xusongpei1995/dataset_train.tf
	 [[node input_pipeline_task0/while/IteratorGetNext (defined at <ipython-input-26-d8416db4f76b>:283) ]]

**Comment by rodrigonogueira4** [comment]
Did you find a solution for this? It seems that it is a permission problem with your bucket. Closing this issue as it appears to be a configuration problem on your side. Feel free to re-open if that is not the case.
