### ISSUE TITLE
Missing 'checkpoint' file in pretrained models

### ISSUE THREAD

**Issue by MateRyze** [nyu-dl/dl4marco-bert#20]
The pretrained base and large BERT models on MS MARCO data contains just the .ckpt files, but the `checkpoint` file is missing.
This file is needed in order to add `estimator.WarmStartSettings` to the `TPUEstimator`

**How to fix this problem?**
Create the `checkpoint` file with following content:
```
model_checkpoint_path: "model.ckpt-100000"
all_model_checkpoint_paths: "model.ckpt-100000"
```

**Comment by rodrigonogueira4** [comment]
I didn't understand the problem. 

If you pass `init_checkpoint` to the scripts `run_msmarco.py` or `run_treccar.py`, everything should work fine.

**Comment by MateRyze** [comment]
> I didn't understand the problem.
> 
> If you pass `init_checkpoint` to the scripts `run_msmarco.py` or `run_treccar.py`, everything should work fine.

I am getting the following error when trying to load the pretrained model:
`ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory gs://bert_msmarco_data/pretrained_models`

Could you please upload the `checkpoint` file?

**Comment by rodrigonogueira4** [comment]
You are seeing the error above because you are passing a folder to `init_checkpoint`, not a file. 
Try passing this:
gs://bert_msmarco_data/pretrained_models/model.ckpt-100000

**Comment by MateRyze** [comment]
> You are seeing the error above because you are passing a folder to `init_checkpoint`, not a file.
> Try passing this:
> gs://bert_msmarco_data/pretrained_models/model.ckpt-100000

Now I am seeing the following error: 
`Error recorded from prediction_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.`

**Comment by rodrigonogueira4** [comment]
Which file are you using as `bert_config_file`?

**Comment by MateRyze** [comment]
> Which file are you using as `bert_config_file`?

gs://cloud-tpu-checkpoints/bert/uncased_L-24_H-1024_A-16/bert_config.json

**Comment by rodrigonogueira4** [comment]
Did you change the Colab in any way? Any change in the model architecture will break the checkpoint reloading script.

**Comment by MateRyze** [comment]
No changes in model architecture, but I am skipping the train phase and the DATA_DIR path is "gs://bert_msmarco_data/tfrecord"

**Comment by rodrigonogueira4** [comment]
Are you running on Colab? If yes, can you share it with me?

**Comment by MateRyze** [comment]
Changing `DATA_DIR` path to "gs://bert_msmarco_data/tfrecord" and changing the path of `OUTPUT_DIR to my GCS bucket helped.  You could add this information to your colab template.
Thank you anyway :)
