### ISSUE TITLE
Is length of most passage short?

### ISSUE THREAD

**Issue by bayou3** [nyu-dl/dl4marco-bert#21]
Hi, I saw "--max_seq_length=512" in your convert to tfrecord .py script. Is the lenght of every passage short? 
I mean, are there some passage with length longer than 512 tokens? If so, do you only use the top 512 tokens of a passage?
 (And a passage means a document/article, right? For this , I want to ask that if a document is too long, it could be truncated into serveral passages, each one of which will get a probability by the model, then how do you process these probabilities of the passages?)

**Comment by rodrigonogueira4** [comment]
Almost none of the documents in both TREC-CAR and MS MARCO had more than 512-64=448 tokens. If a document has more than that, it will be truncated:
https://github.com/nyu-dl/dl4marco-bert/blob/b66077bade69bb3a834e8fb77faaaa31b88205a0/tokenization.py#L32

Truncated here means removing everything after 448 tokens, so a long document will not be split into several passages.

**Comment by bayou3** [comment]
> Almost none of the documents in both TREC-CAR and MS MARCO had more than 512-64=448 tokens. If a document has more than that, it will be truncated:
> https://github.com/nyu-dl/dl4marco-bert/blob/b66077bade69bb3a834e8fb77faaaa31b88205a0/tokenization.py#L32
> 
> Truncated here means removing everything after 448 tokens, so a long document will not be split into several passages.

Thank you very much!
