### ISSUE TITLE
The task is to do a full rank by BERT, given 1 query. Am I right?

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4marco-bert#25]
Full ranking means scoring all the query-passage pairs.
Thank you!
@rodrigonogueira4

**Comment by rodrigonogueira4** [comment]
Full ranking means scoring all passages in the corpus (~8.8M) as opposed to the top-1000 provided by the MS Marco organizers. The way we do it is the following:
Index the 8.8M passages and retrieve the top-100 using BM25. Then we score these top-1000 with BERT.
