### ISSUE TITLE
What is the most popular loss for doc ranking and What is the most popular loss for text similarity?

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4marco-bert#28]
Based on my understanding, both the doc ranking task and text similarity task take sentence pairs as model input. We use different loss to get better result for each of them.
Thank you very much.

**Comment by rodrigonogueira4** [comment]
I think it depends on the problem. Margin loss and cross-entropy loss are popular choices for document ranking. This article provides a nice overview:
https://www.nowpublishers.com/article/Details/INR-016
