### ISSUE TITLE
Big question, BERT ranking need triple to train, but... 

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4marco-bert#30]
https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz
The data above do not contains the negative doc.

@rodrigonogueira4 Thank you!!!

The data is from readme here: https://github.com/nyu-dl/dl4ir-doc2query#ms-marco
![image](https://user-images.githubusercontent.com/4702353/62607708-19450300-b931-11e9-8a08-dfead2ecf999.png)

**Comment by rodrigonogueira4** [comment]
To train the se2seq model you only need pairs of queries and relevant documents, hence you don't need negatives.

Please post doc2query-related questions in that repository:
https://github.com/nyu-dl/dl4ir-doc2query

**Comment by guotong1988** [comment]
Thank you.
