### ISSUE TITLE
Evaluate the trained model on my own trec-car data doesn't work.

### ISSUE THREAD

**Issue by mahsash** [nyu-dl/dl4marco-bert#32]
I managed to run the code on my own data after reading all issues and resolving errors ( using colab).
I uploaded your pre-trained model for trec-car (meta, index, and data files) to my own bucket. I converted my data to tf-record (by using your code) and uploaded it to my bucket too. When I change the "DO_TRAIN" flag to False and run the whole code and get the prediction file, the results are very bad (0.01 MAP!). I guess I'm not using the pre-trained model correctly.
Where I should set the path to the trained model (meta, index, and data files uploaded to my bucket) in colab code?

**Comment by rodrigonogueira4** [comment]
You should set `INIT_CHECKPOINT` to point to the checkpoint. For example:

`INIT_CHECKPOINT = 'gs://path/to/trained/model.ckpt'`

**Comment by mahsash** [comment]
Thanks for your quick reply.
I've set the INIT_CHECKPOINT to point to ckpt-data file, but it says that it should be a .ckpt file (as you mentioned). So, what should I do? Because the model I downloaded from [here](https://drive.google.com/open?id=1fzcL2nzUJMUd0w4J5JIeASSrN4uHlSqP) consists of three files: index, data, and meta file. (So, there is no .ckpt file.)

**Comment by mahsash** [comment]
OK! I got it (from [here](https://github.com/tensorflow/magenta/issues/1369)) I understood that there is no actual .ckpt file and when we set it to point to model.ckpt it used the three separate meta, index, and data file. It's really strange. But, now it works correctly.
Thanks again!

**Comment by rodrigonogueira4** [comment]
Yeah, checkpoint loading is confusing in TensorFlow :)
I'm glad it worked!
