### ISSUE TITLE
How to get the bert_config.json file

### ISSUE THREAD

**Issue by aizest** [nyu-dl/dl4marco-bert#33]
I'm trying to run the treccar on my own GPU. But I couldn't find the "uncased_L-24_H-1024_A-16/bert_config.json" in the provided code and pre-trained BERT model. Where can we get a copy? Thanks in advance.

**Comment by rodrigonogueira4** [comment]
It is the same config file used by the original BERT repository (https://github.com/google-research/bert):

https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-24_H-1024_A-16.zip

**Comment by aizest** [comment]
Great! Thanks a lot!
