### ISSUE TITLE
Config files in zipped models

### ISSUE THREAD

**Issue by cristinadece** [nyu-dl/dl4marco-bert#37]
Could you please add the config and vocab files to the BERT_Large_MSMARCO and BERT_Large_trained_on_TREC_CAR models?

Thanks!

----- 
I added `bert_config.json` to `BERT_Base_trained_on_MSMARCO.zip`. You should not see the error anymore if you pass it to `--bert_config_file`

_Originally posted by @rodrigonogueira4 in https://github.com/nyu-dl/dl4marco-bert/issues/35#issuecomment-564683088_

**Comment by rodrigonogueira4** [comment]
Sure, I updated the files. I'm sorry it took so long.
