### ISSUE TITLE
How to keep fine-tuning the MS MARCO-based bert model

### ISSUE THREAD

**Issue by Eilons** [nyu-dl/dl4marco-bert#40]
Hi!
I would like to use your model that was fine-tuned on MS MARCO and to fine-tune it using another passage-based collection. How should I use your code to achieve this? should I only pass your fine-tuned model as an init_checkpoint?
In addition, does the training process make use of negative query-passage pairs or should I feed the model with only relevant passages?
Thanks!

**Comment by rodrigonogueira4** [comment]
Hi @Eilons, yes and yes for the first two questions.
Regarding the last question, you also need to train the model with negative pairs.

**Comment by Eilons** [comment]
Thank you very much!
