### ISSUE TITLE
Access to gs://bert_msmarco_data/tfrecord denied 

### ISSUE THREAD

**Issue by Yastil** [nyu-dl/dl4marco-bert#41]
Hi, it seems that the Google cloud storage for the MS MARCO data is no longer available. Will you be allowing public access once again in the near future?

**Comment by rodrigonogueira4** [comment]
Sorry about the inconvenience. Could you please try again?

**Comment by Yastil** [comment]
Thank you for the quick response! The directory is now accessible.
