### ISSUE TITLE
Standard TREC format

### ISSUE THREAD

**Issue by Yastil** [nyu-dl/dl4marco-bert#42]
Hi, 
I am trying to get the msmarco_file into the standard TREC format;
query_id   Q0   doc-id   rank   score  exp 

I tried using;
msmarco_file.write("\t".join((query_id, 'Q0', doc_id, str(rank), str(score[doc_idx]), 'run1')) + "\n")

However the scores appear to be negative, which causes trec_eval to fail. Is there perhaps another variable that should be used to obtain the score for each query-document pair?

**Comment by rodrigonogueira4** [comment]
You can do `score = 1/rank`

**Comment by Yastil** [comment]
Thank you x 2!
