### ISSUE TITLE
Difference between evaluation done using run treccar.py file and using the Anserini Script

### ISSUE THREAD

**Issue by SinghShreyas** [nyu-dl/dl4marco-bert#52]
@rodrigonogueira4 

Dear Rodrigo,

Fisrt of all, thanks for providing the code. It is of great help.

I just had one confusion. What is difference between the model evaluation done using run_treccar.py file and with anserini evaluation script. Bit confused about this. Please help me in this regard.

Thanks!

Best Regards,
Shreyas

**Comment by rodrigonogueira4** [comment]
Hi Shreyas, the evaluation with run_treccar.py outputs only a few metrics but it has the convenience that we can train and evaluate the model using the same script. Anserini uses trec_eval, which provides more metrics, but it needs first to generate a "run" file, so it is less convenient.

**Comment by SinghShreyas** [comment]
Hi Rodrigo,

Thanks a lot for your reply. That cleared my confusion. Really appreciate it.
